services:
  green-coding-postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
      args:
        - postgres_pw=cccvvv
    container_name: green-coding-postgres-container
    restart: always
    volumes:
      - green-coding-postgres-data:/var/lib/postgresql/14/main
    networks:
      - green-coding-net
    expose:
      - 5432
    ports:
      - 5432:5432
  green-coding-nginx-gunicorn:
    build:
      context: .
      dockerfile: Dockerfile-gunicorn-nginx
      args:
        - postgres_pw=cccvvv
    container_name: green-coding-nginx-gunicorn-container
    networks:
      - green-coding-net
    depends_on:
      - green-coding-postgres
    ports:
      - 8000:80
    restart: always
networks:
  green-coding-net:
volumes:
  green-coding-postgres-data: